version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_DB: ${PSQL_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sdc-aerio-all.sql:/docker-entrypoint-initdb.d/sdc-aerio-all.sql


