version: '3'
services:
  server:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./aerio_dump.sql:/docker-entrypoint-initdb.d/aerio_dump.sql
